const seedData = {
  college: {
    name: "Колледж: пилот компетентностной платформы",
    department: "Кафедра экономики, сервиса и торговли",
    specialty: {
      code: "38.02.08",
      name: "Торговое дело",
      duration: "2 года 10 месяцев",
      format: "очная форма обучения",
      pilotYear: "2026",
    },
  },
  roles: [
    { id: "student", title: "Студент", account: "student@demo.ru", userId: "s1" },
    { id: "teacher", title: "Преподаватель", account: "teacher@demo.ru", userId: "t1" },
    { id: "head", title: "Заведующий", account: "head@demo.ru", userId: "h1" },
    { id: "methodologist", title: "Методист", account: "method@demo.ru", userId: "m1" },
    { id: "director", title: "Директор", account: "director@demo.ru", userId: "d1" },
    { id: "employer", title: "Работодатель", account: "employer@demo.ru", userId: "emp1" },
    { id: "admin", title: "Администратор", account: "admin@demo.ru", userId: "a1" },
  ],
  groups: [
    { id: "td-26", name: "ТД-26", year: 1, specialtyCode: "38.02.08", curator: "Иванова Мария Сергеевна" },
  ],
  students: [
    { id: "s1", name: "Анна Соколова", groupId: "td-26", email: "student@demo.ru", publicProfile: true, portfolioAccess: "public", employmentStatus: "готова к практике" },
    { id: "s2", name: "Максим Громов", groupId: "td-26", email: "gromov@demo.ru", publicProfile: false, portfolioAccess: "college", employmentStatus: "нужна доработка" },
    { id: "s3", name: "Дарья Лебедева", groupId: "td-26", email: "lebedeva@demo.ru", publicProfile: true, portfolioAccess: "partners", employmentStatus: "готова к практике" },
    { id: "s4", name: "Илья Морозов", groupId: "td-26", email: "morozov@demo.ru", publicProfile: false, portfolioAccess: "request", employmentStatus: "формирует портфолио" },
    { id: "s5", name: "Полина Кузнецова", groupId: "td-26", email: "kuznetsova@demo.ru", publicProfile: true, portfolioAccess: "public", employmentStatus: "готова к стажировке" },
    { id: "s6", name: "Егор Орлов", groupId: "td-26", email: "orlov@demo.ru", publicProfile: false, portfolioAccess: "college", employmentStatus: "нужна доработка" },
    { id: "s7", name: "Ксения Федорова", groupId: "td-26", email: "fedorova@demo.ru", publicProfile: true, portfolioAccess: "partners", employmentStatus: "готова к практике" },
    { id: "s8", name: "Никита Волков", groupId: "td-26", email: "volkov@demo.ru", publicProfile: false, portfolioAccess: "request", employmentStatus: "формирует портфолио" },
    { id: "s9", name: "Алина Павлова", groupId: "td-26", email: "pavlova@demo.ru", publicProfile: true, portfolioAccess: "public", employmentStatus: "готова к стажировке" },
    { id: "s10", name: "Роман Новиков", groupId: "td-26", email: "novikov@demo.ru", publicProfile: false, portfolioAccess: "college", employmentStatus: "нужна доработка" },
  ],
  teachers: [
    { id: "t1", name: "Иванова Мария Сергеевна", disciplines: ["op01", "pm01", "up01"] },
    { id: "t2", name: "Петров Алексей Викторович", disciplines: ["op02", "op04", "pm03"] },
    { id: "t3", name: "Смирнова Елена Павловна", disciplines: ["op05", "pm02", "pp01"] },
  ],
  disciplines: [
    { id: "oup15", code: "ОУП.15", name: "Введение в специальность", cycle: "общеобразовательный", hours: 72, semester: 1, type: "course" },
    { id: "oup13", code: "ОУП.13", name: "Информатика", cycle: "общеобразовательный", hours: 108, semester: 1, type: "course" },
    { id: "op01", code: "ОП.01", name: "Экономика и основы анализа финансово-хозяйственной деятельности торговой организации", cycle: "общепрофессиональный", hours: 128, semester: 2, type: "course" },
    { id: "op02", code: "ОП.02", name: "Прикладные компьютерные программы в профессиональной деятельности", cycle: "общепрофессиональный", hours: 96, semester: 2, type: "course" },
    { id: "op03", code: "ОП.03", name: "Эксплуатация торгово-технологического оборудования и охрана труда", cycle: "общепрофессиональный", hours: 96, semester: 3, type: "course" },
    { id: "op04", code: "ОП.04", name: "Автоматизация торгово-технологических процессов", cycle: "общепрофессиональный", hours: 108, semester: 3, type: "course" },
    { id: "op05", code: "ОП.05", name: "Основы предпринимательства", cycle: "общепрофессиональный", hours: 72, semester: 3, type: "course" },
    { id: "op06", code: "ОП.06", name: "Правовое обеспечение профессиональной деятельности", cycle: "общепрофессиональный", hours: 72, semester: 4, type: "course" },
    { id: "op07", code: "ОП.07", name: "Финансы, налоги и налогообложение", cycle: "общепрофессиональный", hours: 72, semester: 4, type: "course" },
    { id: "pm01", code: "ПМ.01", name: "Организация и осуществление торговой деятельности", cycle: "профессиональный модуль", hours: 288, semester: 4, type: "module" },
    { id: "pm02", code: "ПМ.02", name: "Организация и осуществление предпринимательской деятельности в сфере торговли", cycle: "профессиональный модуль", hours: 216, semester: 5, type: "module" },
    { id: "pm03", code: "ПМ.03", name: "Организация и осуществление интернет-маркетинга", cycle: "профессиональный модуль", hours: 216, semester: 5, type: "module" },
    { id: "up01", code: "УП.01.01", name: "Учебная практика по торговой деятельности", cycle: "практика", hours: 72, semester: 4, type: "practice" },
    { id: "up02", code: "УП.02.01", name: "Учебная практика по предпринимательству", cycle: "практика", hours: 72, semester: 5, type: "practice" },
    { id: "up03", code: "УП.03.01", name: "Учебная практика по интернет-маркетингу", cycle: "практика", hours: 72, semester: 5, type: "practice" },
    { id: "pp01", code: "ПП.01.01", name: "Производственная практика по торговой деятельности", cycle: "практика", hours: 108, semester: 6, type: "practice" },
    { id: "pp02", code: "ПП.02.01", name: "Производственная практика по предпринимательству", cycle: "практика", hours: 108, semester: 6, type: "practice" },
    { id: "pp03", code: "ПП.03.01", name: "Производственная практика по интернет-маркетингу", cycle: "практика", hours: 108, semester: 6, type: "practice" },
  ],
  competencies: [
    {
      id: "ok01",
      code: "ОК.01",
      title: "Выбирать способы решения задач профессиональной деятельности",
      cluster: "универсальные",
      knowledge: ["виды профессиональных задач", "алгоритмы принятия решений"],
      skills: ["анализировать условия задачи", "выбирать инструменты решения"],
      habits: ["фиксировать результат", "проверять качество решения"],
      indicators: ["формулирует задачу", "обосновывает выбранный способ", "оценивает результат"],
    },
    {
      id: "ok02",
      code: "ОК.02",
      title: "Использовать цифровые средства и информацию",
      cluster: "универсальные",
      knowledge: ["источники данных", "правила работы с цифровыми сервисами"],
      skills: ["искать и структурировать информацию", "работать с таблицами и учетными системами"],
      habits: ["соблюдать цифровую гигиену", "хранить подтверждающие материалы"],
      indicators: ["использует ПО в задаче", "обрабатывает данные", "прикрепляет цифровой результат"],
    },
    {
      id: "ok03",
      code: "ОК.03",
      title: "Планировать профессиональное и личностное развитие",
      cluster: "универсальные",
      knowledge: ["траектории развития", "критерии профессиональной готовности"],
      skills: ["ставить цели", "планировать шаги развития"],
      habits: ["обновлять портфолио", "сравнивать текущий уровень с целевым"],
      indicators: ["видит дефициты", "обновляет план", "использует обратную связь"],
    },
    {
      id: "pk01",
      code: "ПК.01",
      title: "Организовывать торговую деятельность и обслуживание покупателей",
      cluster: "профессиональные",
      knowledge: ["этапы торгового процесса", "правила обслуживания покупателей"],
      skills: ["готовить торговое пространство", "консультировать покупателя", "оформлять продажу"],
      habits: ["соблюдать стандарты сервиса", "контролировать качество обслуживания"],
      indicators: ["выстраивает процесс продажи", "работает с возражениями", "соблюдает регламенты"],
    },
    {
      id: "pk02",
      code: "ПК.02",
      title: "Вести учет, анализ и документооборот торговой организации",
      cluster: "профессиональные",
      knowledge: ["первичные документы", "показатели финансово-хозяйственной деятельности"],
      skills: ["оформлять документы", "анализировать продажи и остатки", "использовать учетное ПО"],
      habits: ["проверять полноту данных", "соблюдать сроки документооборота"],
      indicators: ["готовит документы", "объясняет показатели", "находит отклонения"],
    },
    {
      id: "pk03",
      code: "ПК.03",
      title: "Организовывать предпринимательскую деятельность в сфере торговли",
      cluster: "профессиональные",
      knowledge: ["модели торгового бизнеса", "налоги и правовые формы", "финансовое планирование"],
      skills: ["рассчитывать экономику проекта", "готовить бизнес-гипотезу", "презентовать решение"],
      habits: ["проверять спрос", "считать риски", "собирать обратную связь"],
      indicators: ["описывает бизнес-модель", "считает выручку и расходы", "защищает проект"],
    },
    {
      id: "pk04",
      code: "ПК.04",
      title: "Использовать интернет-маркетинг и цифровые каналы продаж",
      cluster: "профессиональные",
      knowledge: ["каналы продвижения", "воронка продаж", "метрики интернет-маркетинга"],
      skills: ["создавать контент", "планировать кампанию", "оценивать эффективность"],
      habits: ["тестировать гипотезы", "вести аналитику", "улучшать коммуникацию"],
      indicators: ["собирает медиаплан", "настраивает цифровой канал", "оценивает метрики"],
    },
  ],
  links: [
    { disciplineId: "oup15", competencyId: "ok01", weight: 0.45 },
    { disciplineId: "oup15", competencyId: "ok03", weight: 0.35 },
    { disciplineId: "oup13", competencyId: "ok02", weight: 0.55 },
    { disciplineId: "op01", competencyId: "pk02", weight: 0.55 },
    { disciplineId: "op01", competencyId: "pk03", weight: 0.25 },
    { disciplineId: "op02", competencyId: "ok02", weight: 0.45 },
    { disciplineId: "op02", competencyId: "pk02", weight: 0.35 },
    { disciplineId: "op03", competencyId: "pk01", weight: 0.55 },
    { disciplineId: "op04", competencyId: "ok02", weight: 0.35 },
    { disciplineId: "op04", competencyId: "pk04", weight: 0.45 },
    { disciplineId: "op05", competencyId: "pk03", weight: 0.55 },
    { disciplineId: "op06", competencyId: "pk02", weight: 0.3 },
    { disciplineId: "op06", competencyId: "pk03", weight: 0.25 },
    { disciplineId: "op07", competencyId: "pk02", weight: 0.4 },
    { disciplineId: "op07", competencyId: "pk03", weight: 0.35 },
    { disciplineId: "pm01", competencyId: "pk01", weight: 0.8 },
    { disciplineId: "pm01", competencyId: "pk02", weight: 0.4 },
    { disciplineId: "pm02", competencyId: "pk03", weight: 0.85 },
    { disciplineId: "pm03", competencyId: "pk04", weight: 0.85 },
    { disciplineId: "up01", competencyId: "pk01", weight: 0.9 },
    { disciplineId: "up02", competencyId: "pk03", weight: 0.85 },
    { disciplineId: "up03", competencyId: "pk04", weight: 0.85 },
    { disciplineId: "pp01", competencyId: "pk01", weight: 1 },
    { disciplineId: "pp02", competencyId: "pk03", weight: 1 },
    { disciplineId: "pp03", competencyId: "pk04", weight: 1 },
  ],
  evidence: [
    { id: "e1", studentId: "s1", disciplineId: "oup15", title: "Диагностика входа в специальность", type: "grade", score: 86, date: "2026-09-16", status: "verified_by_teacher", verifier: "t1", source: "оценка" },
    { id: "e2", studentId: "s1", disciplineId: "op01", title: "Расчет показателей торговой организации", type: "lab", score: 91, date: "2026-11-04", status: "verified_by_teacher", verifier: "t1", source: "практическая работа" },
    { id: "e3", studentId: "s1", disciplineId: "op02", title: "Таблица учета продаж и остатков", type: "project", score: 88, date: "2026-11-18", status: "verified_by_methodologist", verifier: "m1", source: "файл" },
    { id: "e4", studentId: "s1", disciplineId: "pm01", title: "Сценарий обслуживания покупателя", type: "practice", score: 93, date: "2027-02-10", status: "submitted", verifier: "", source: "демонстрация" },
    { id: "e5", studentId: "s1", disciplineId: "pm02", title: "Мини-бизнес торговой точки", type: "project", score: 82, date: "2027-03-12", status: "needs_revision", verifier: "h1", source: "проект" },
    { id: "e6", studentId: "s1", disciplineId: "pm03", title: "Контент-план интернет-продаж", type: "contest", score: 96, date: "2027-04-05", status: "verified_by_department_head", verifier: "h1", source: "конкурс" },
    { id: "e7", studentId: "s2", disciplineId: "op01", title: "Анализ выручки", type: "lab", score: 73, date: "2026-11-04", status: "verified_by_teacher", verifier: "t1", source: "практическая работа" },
    { id: "e8", studentId: "s3", disciplineId: "pm01", title: "Оформление продажи", type: "practice", score: 89, date: "2027-02-10", status: "submitted", verifier: "", source: "практика" },
    { id: "e9", studentId: "s4", disciplineId: "op05", title: "Бизнес-гипотеза", type: "project", score: 78, date: "2027-03-02", status: "verified_by_teacher", verifier: "t3", source: "проект" },
    { id: "e10", studentId: "s5", disciplineId: "pm03", title: "Маркетинговая кампания", type: "contest", score: 94, date: "2027-04-05", status: "verified_by_department_head", verifier: "h1", source: "конкурс" },
  ],
  statusWeights: {
    draft: 0.2,
    submitted: 0.35,
    needs_revision: 0.25,
    verified_by_teacher: 0.7,
    verified_by_department_head: 0.8,
    verified_by_methodologist: 0.75,
    verified_by_employer: 0.9,
    rejected: 0,
    archived: 0,
  },
  typeWeights: {
    grade: 0.75,
    lab: 0.9,
    project: 1.05,
    practice: 1.2,
    contest: 1.25,
    employer_review: 1.3,
  },
  employers: [
    { id: "emp1", name: "Торговая сеть «Партнер Маркет»", contact: "hr@partner-market.demo", status: "moderated", industry: "розничная торговля", access: "college_and_partners" },
    { id: "emp2", name: "Маркетплейс «Север Онлайн»", contact: "talent@sever.demo", status: "pending", industry: "e-commerce", access: "request_only" },
  ],
  employerRequests: [
    { id: "req1", employerId: "emp1", title: "Практиканты в торговый зал", specialtyCode: "38.02.08", course: 1, required: ["pk01", "ok02"], desired: ["pk02"], minLevel: 35, format: "производственная практика", status: "active", createdAt: "2026-12-10" },
    { id: "req2", employerId: "emp1", title: "Стажировка junior интернет-маркетолога", specialtyCode: "38.02.08", course: 1, required: ["pk04", "ok02"], desired: ["ok03", "pk03"], minLevel: 30, format: "стажировка", status: "draft", createdAt: "2027-01-18" },
  ],
  invitations: [
    { id: "inv1", requestId: "req1", employerId: "emp1", studentId: "s1", type: "practice", status: "sent", date: "2027-02-18", note: "Приглашение на собеседование перед практикой" },
    { id: "inv2", requestId: "req2", employerId: "emp1", studentId: "s5", type: "internship", status: "accepted", date: "2027-03-02", note: "Тестовое задание по контент-плану" },
  ],
  employerReviews: [
    { id: "rev1", employerId: "emp1", studentId: "s1", disciplineId: "pp01", competencyIds: ["pk01", "ok02"], score: 92, status: "submitted", date: "2027-03-12", text: "Уверенно работает с покупателем, быстро осваивает учетные инструменты." },
  ],
  reports: [
    { id: "r1", title: "Отчет по группе ТД-26", scope: "group", owner: "head", format: "PDF", status: "ready" },
    { id: "r2", title: "Методическое покрытие компетенций", scope: "methodology", owner: "methodologist", format: "Excel", status: "ready" },
    { id: "r3", title: "Запросы работодателей и дефициты", scope: "employers", owner: "director", format: "PDF", status: "draft" },
  ],
};
